//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccsess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRows
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
