//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccsess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        public virtual Product Product { get; set; }
    }
}
